baseurl: "https://www.gophercon.org.il/"
title: "Conference name"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Gophercon Israel 2021"
  Description: "Best Go Conference in Israel"
  Date: "February 11"
  # Price: "100NIS" # If your event is free, just comment this line
  Venue: "Online"
  Address: "Boulevard Kukulcan, 30"
  City:  "Everywhere"
  State: "Israel"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    # - location
    # - speakers
    - schedule
    - sponsors
    # - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Submit a workshop!"
  #   link: "https://www.papercall.io/gcil-2021"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  # ForkButton:
  #   repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Cloudinary"
      logo: "/img/cloudinary.png"
      url: "https://cloudinary.com/careers"
      body:
        - text: "Cloudinary’s mission is to empower companies to deliver visual experiences that inspire and connect by unleashing the full potential of their media. With more than 40 billion assets under management and 7,000 customers worldwide, Cloudinary is the industry standard for developers, creators, and marketers looking to upload, store, transform, manage, and deliver images and videos online. As a result, leading brands like Atlassian, Bleacher Report, Grubhub, Hinge, Lyft, NBC, Mediavine, Peloton, Petco, and Under Armour are seeing significant business value in using Cloudinary, including faster time to market, higher user satisfaction, and increased engagement and conversions."
    - name: "DoiT"
      logo: "/img/doit.png"
      url: "https://grnh.se/6cc8447d3us"
      body:
        - text: "DoiT International, the strategic partner of Google Cloud and Amazon Web Services, provides cloud expertise, proprietary cloud optimization, and governance software. The company tackles complex problems of scale for customers, using expertise in machine learning, algorithms, complexity analysis, and system design."
        - text: "Founded in 2011, DoiT International operates in nearly 70 countries, including the United States, the United Kingdom, Germany, France, Australia, and Israel. For more information, please visit www.doit-intl.com."
    - name: "Palo Alto Networks"
      logo: "/img/paloalto.png"
      url: "http://bit.ly/32UOuhh"
      body:
        - text: "Palo Alto Networks is the largest Cyber Security company in the world that helps tens of thousands of organizations worldwide prevent cyber breaches.
                  At Palo Alto Networks® everything starts and ends with our mission:
                  Being the cybersecurity partner of choice, protecting our digital way of life.
                  We have the vision of a world where each day is safer and more secure than the one before. These aren’t easy goals to accomplish – but we’re not here for easy. We’re here for the better. We are a company built on the foundation of challenging and disrupting the way things are done, and we’re looking for innovators who are as committed to shaping the future of cybersecurity as we are.  
                  As our founder and CTO Nir Zuk once said: \"the hacker only needs to succeed once, and we need to succeed 100% of the time!\""
    
  # List of Partners
  Partners:
    # - name: "Hugo"
    #   logo: "/img/hugo.jpg"
    #   url: "https://gohugo.io"
    # - name: "BrazilJS"
    #   logo: "/img/partner.png"
    #   url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Miki Tebeka"
      presentation:
        title: "The Daily Go"
        description: "Writing code is hard, maintaining it is even harder. In this workshop we’ll cover the daily tasks a typical gopher goes through (aka “best practices”) such as testing, documenting..."
        time: "09:30 12:30"
        language: "Hebrew"
    
    - name: "Amit Davidson"
      presentation:
        title: "Static Analysis with Go - A Practitioner's Guide "
        description: "Static code analyzers are valuable tools that are easy to write and serve as low-effort bug catchers. Wonder how your IDE knows what it should be yelling at you? Want to make sure no bug (well, many bugs) make it into production? This workshop will guide you in creating your own analyzer in Go!"
        time: "09:30 12:30"
        language: "English"

    - name: "Preslav Mihaylov"
      presentation:
        title: "Hands-on gRPC with Go"
        description: "In this workshop, we’ll go through a small micro services setup and we’ll focus on establishing the communication between them using the gRPC protocol. We’ll explore all communication types gRPC supports and by the end, you’ll have sufficient knowledge to integrate gRPC in your own infrastructure."
        time: "13:00 16:00"
        language: "English"
    
    - name: "Eran Levy"
      presentation:
        title: "Building cloud native services in Go"
        description: "Cloud brings with it many benefits but also challenges. Building cloud native services is challenging. Even though the general guidelines are not development language dependent, there are still many differences. The workshop will focus on building an e2e Go cloud native service from scratch."
        time: "13:00 16:00"
        language: "English"
         

    - name: "Bill Kennedy"
      photo: "/img/bill_kennedy.jpg"
      bio: "Walking the line between correctness and comprehension, youtube.ardanlabs.com"
      company: "Ardan Labs"
      link:
        href: "http://twitter.com/goinggodotnet"
        text: "@goinggodotnet"
      presentation:
        title: "Tracing and Profiling in Go"
        description: "In this workshop Bill will walk you through the Go tooling on tracing and profiling.  Along the way, he will teach about escape analysis, garbage collection, and compiler optimizations"
        time: "16:30 20:30"
        language: "English"