baseurl: "https://www.gophercon.org.il/"
title: "GopherCon Israel 2025"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"
enableRobotsTXT: true

GoogleAnalytics: "UA-125301893-1"

params:
  # Conference info
  Name: "GopherCon Israel 2025"
  Description: "Best Go Conference in Israel"
  Date: "May 25"
  # Price: "100NIS" # If your event is free, just comment this line
  Venue: "Expo - Bitan 10"
  # Address: "Expo - Bitan 10"
  placebounds: "!1m14!1m12!1m3!1d876.4370918050947!2d34.807993055863754!3d32.10458223177085!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sil!4v1724317817107!5m2!1sen!2sil"
  City: "Tel Aviv"
  State: "Israel"
  Images: ["/img/badge.jpg"]
  # GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    # - schedule
    # - sponsors
    - team
    - tweets
    # - partners
    # - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"
    team: "Team"
  
  # The Call To Action button at the header,
  # CallToAction:
  #   text: "Become a Sponsor"
  #   link: "/sponsor"

   # The Call To Action button at the header,
  CallForPaper:
    text: "2025 Photos"
    link: "https://photos.app.goo.gl/f7cb8nFzQKhkFNXN8"

  # The Call To Action button at the header,
  VideoButton:
    text: "2024 Videos"
    link: "https://www.youtube.com/playlist?list=PLRM-8sTy13XtQu_kYd-7e_HbKpXLTWuy1"

  # The Call For Paper button at the header,
  # CallForPaper:
  #   text: "Apply to Speak"
  #   link: "https://sessionize.com/gophercon-israel-2025"

  # The tickets button at the header,
  # Tickets:
  #   text: "Purchase Ticket"
  #   link: "https://www.eventer.co.il/gc2025"

  # List of Sponsors
  Sponsors:
    gold:
      - name: "AppsFlyer"
        logo: "/img/appsflyer-logo.png"
        url: "https://careers.appsflyer.com/"
        body:
          - text: "The world's leading brands use AppsFlyer to make good choices for their business and customers, through privacy-preserving measurement, analytics and engagement technologies."
      - name: "Google"
        logo: "/img/google-logo.svg"
        url: "https://careers.google.com/"
        body:
          - text: ""
      - name: "Descope"
        logo: "/img/descope-logo.svg"
        url: "https://www.descope.com/"
        body:
          - text: "Descope helps every developer build secure, frictionless authentication and user journeys for any application. Our no-code workflow builder, SDKs, and APIs enable developers to easily create and customize authentication flows for every user interaction. Designed by security experts, Descope also protects against account takeover fraud, session theft, and bot attacks on login pages. Founded in 2022, Descope is headquartered in Los Altos, CA and is a member of the FIDO Alliance. To learn more, visit https://www.descope.com."
      - name: "Tenable"
        logo: "/img/tenable-logo.png"
        url: "https://www.tenable.com/careers/search?country=Israel"
        body:
          - text: "Tenable is the exposure management company, exposing and closing the cybersecurity gaps that erode business value, reputation and trust. The company's AI-powered exposure management platform radically unifies security visibility, insight and action across the attack surface, equipping modern organizations to protect against attacks from IT infrastructure to cloud environments to critical infrastructure and everywhere in between. By protecting enterprises from security exposure, Tenable reduces business risk for more than 44,000 customers around the globe. Learn more at tenable.com."
    silver:
      - name: "RedHat"
        logo: "/img/redhat-logo.svg"
        url: "https://www.redhat.com/en/jobs"
        body:
          - text: "Red Hat is the world's leading provider of enterprise open-source solutions, using a community-powered approach to deliver high-performing Linux, cloud, container, and Kubernetes technologies. We help customers standardize across environments, develop cloud-native applications, and integrate, automate, secure, and manage complex environments with award-winning support, training, and consulting services."
      - name: "Island"
        logo: "/img/island-logo.svg"
        url: "https://www.island.io/careers"
        body:
          - text: 'Island, founded nearly four years ago by two visionary entrepreneurs: Dan Amiga, who already accomplished impressive exits and is considered one of the leading names in the local industry, and Mike, the former COO of Symantec. Island is supported by top investors like Sequoia, Insights, and Cyberstarts. Recently, Island raised investments at a valuation of nearly $3 billion, serving leading global companies, including those from the Fortune 100.Island goes beyond cybersecurity. Its innovative browser not only protects organizations but also enhances user experience while offering transparency and control. The browser allows employees to work quickly and securely, accessing all organizational services without unnecessary delays or blocks.Developing an enterprise browser is highly complex, requiring expertise in multiple areas, including advanced web solutions like SSE (Server-Sent Events), protection of sensitive data using technologies like DLP (Data Loss Prevention), and AI integration for improved user experience and productivity. Moreover, creating a browser that secures user activity without harming performance or slowing down work requires an advanced combination of security technologies with a smooth user experience. All that while keeping full transparency and control to the organization. Island`s browser secures users without compromising performance, setting it apart as a pioneer in the field.Island has created a new category called "Enterprise Browsers", with Gartner predicting that browsers will be the central platform in organizations by 2030.The company has around 100 developers in Israel, with the rest of the team based in the U.S.'

  # List of Partners
  Partners:

  Team:
    - name: Miki Tebeka
      photo: "img/miki-tebeka.jpg"
      linkedin: "https://www.linkedin.com/in/mikitebeka/"
      twitter: "https://twitter.com/tebeka"
    - name: Eliran Bivas
      photo: "img/eliran-bivas.jpg"
      linkedin: "https://www.linkedin.com/in/bivas/"
      twitter: "https://twitter.com/bivas"
    - name: "David Bordeynik"
      photo: "img/david-bord.jpg"
      linkedin: "https://www.linkedin.com/in/david-b-270b0415"
    - name: Yoni Davidson
      photo: "img/yoni-davidson.jpg"
      linkedin: "https://www.linkedin.com/in/yoni-davidson-35b53222"
      twitter: "https://twitter.com/yonidavidson"
    - name: Shlomi Noach
      photo: "img/shlomi-noach.jpg"
      linkedin: "https://www.linkedin.com/in/shlominoach"
    - name: "Nahshon Unna-Tsameret"
      photo: "img/nashon-unna-tsameret.jpg"
      linkedin: "https://www.linkedin.com/in/nahsh"
    - name: "Orit Wasserman"
      photo: "img/orit-wasserman.jpg"
      linkedin: "https://www.linkedin.com/in/orit-wasserman-73547"